// <auto-generated />
#nullable enable
namespace worker.platform.application.JobsDeals.Mappers
{
    public partial class JobAssignmentMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.1.1.0")]
        public partial global::worker.platform.domain.Entities.JobRequest? MapAddRequestDto(global::worker.platform.application.JobsDeals.DTOs.AddJobRequestDto? addJobRequestDto)
        {
            if (addJobRequestDto == null)
                return default;
            var target = new global::worker.platform.domain.Entities.JobRequest();
            target.TaskTypeId = addJobRequestDto.TaskTypeId;
            target.Details = addJobRequestDto.Details;
            target.StartDate = addJobRequestDto.StartDate;
            target.CustomerId = addJobRequestDto.CustomerId;
            target.CityId = addJobRequestDto.CityId;
            if (addJobRequestDto.Params != null)
            {
                target.Params = MapToListOfJobRequestParams(addJobRequestDto.Params);
            }
            else
            {
                target.Params = null;
            }
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.1.1.0")]
        public partial global::worker.platform.domain.Entities.JobResponse? MapJobApplicationToResponse(global::worker.platform.application.JobsDeals.DTOs.JobResponseDto? jobResponseDto)
        {
            if (jobResponseDto == null)
                return default;
            var target = new global::worker.platform.domain.Entities.JobResponse();
            target.Message = jobResponseDto.Message;
            target.SuggestedPrice = jobResponseDto.SuggestedPrice;
            target.EstimatedTime = jobResponseDto.EstimatedTime;
            target.EstimatedTimeUnit = jobResponseDto.EstimatedTimeUnit;
            target.JobRequestId = jobResponseDto.JobRequestId;
            target.WorkerId = jobResponseDto.WorkerId;
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.1.1.0")]
        private global::System.Collections.Generic.List<global::worker.platform.domain.ValueObjects.JobRequestParams?> MapToListOfJobRequestParams(global::worker.platform.application.JobsDeals.DTOs.JobRequestParamsDto source)
        {
            var target = new global::System.Collections.Generic.List<global::worker.platform.domain.ValueObjects.JobRequestParams?>();
            return target;
        }
    }
}