// <auto-generated />
#nullable enable
namespace worker.platform.application.Users.Mappers
{
    public partial class UserMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.1.1.0")]
        public partial global::worker.platform.domain.Entities.User? SignupUserDtoToUser(global::worker.platform.application.Users.DTOs.SignUpUserDto? userDto)
        {
            if (userDto == null)
                return default;
            var target = new global::worker.platform.domain.Entities.User();
            target.Email = userDto.Email;
            target.PasswordHash = MapPassword(userDto.Password);
            target.RoleId = userDto.RoleId;
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.1.1.0")]
        public partial global::worker.platform.domain.Entities.Worker? WorkerProfileDtoToWorker(global::worker.platform.application.Users.DTOs.WorkerProfileDto? workerProfileDto)
        {
            if (workerProfileDto == null)
                return default;
            var target = new global::worker.platform.domain.Entities.Worker();
            target.Id = workerProfileDto.Id;
            target.FirstName = workerProfileDto.FirstName;
            target.LastName = workerProfileDto.LastName;
            target.PhoneNumber = workerProfileDto.PhoneNumber;
            target.Address = workerProfileDto.Address;
            target.CIN = workerProfileDto.CIN;
            target.JobCategoryId = workerProfileDto.JobCategoryId;
            target.CityId = workerProfileDto.LivingCityId;
            target.UserId = workerProfileDto.UserId;
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.1.1.0")]
        public partial global::worker.platform.application.BackOffice.DTOs.UserDto? UserDtoToUserDto(global::worker.platform.domain.Entities.User? user)
        {
            if (user == null)
                return default;
            var target = new global::worker.platform.application.BackOffice.DTOs.UserDto(user.Email, user.Role?.Name);
            return target;
        }
    }
}